apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-demo-exteral-secret # arbitrary
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-demo-secret-store # name of the ESO SecretStore we created
    kind: SecretStore
  target:
    name: eso-demo-secret       # Kubernetes secret name
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: eso-demo-secret      # the name of secret in AWS Secrets Manager