apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eso-demo-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-demo-secret-store-access-key
            key: access-key
          secretAccessKeySecretRef:
            name: eso-demo-secret-store-access-key
            key: secret-access-key