kind: Service
apiVersion: v1
metadata:
  name: my-deployment
  labels:
    app: sample
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: my-service-account
      volumes:
      - name: my-secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: my-secret-provider-class
      containers:
      - name: my-deployment
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true

